---
version: 1.1.x.{build}
branches:
  only:
    - master
    - release
skip_commits:
  message: /^\(?doc\)?.*/
clone_depth: 10
init:
  - SET
  - 'mkdir C:\ProgramData\PuppetLabs\code && exit 0'
  - 'mkdir C:\ProgramData\PuppetLabs\facter && exit 0'
  - 'mkdir C:\ProgramData\PuppetLabs\hiera && exit 0'
  - 'mkdir C:\ProgramData\PuppetLabs\puppet\var && exit 0'
test_script:
  - pdk validate --puppet-version=7
  - pdk test run --puppet-version=7
notifications:
  - provider: Email
    to:
      - puppet-modulebouw@kpn.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false