---
version: 1.1.x.{build}
branches:
  only:
    - master
    - upgrade
skip_commits:
  message: /^\(?doc\)?.*/
platform:
  - x64
configuration: Debug
clone_depth: 10
image: 'Ubuntu2004'
install:
  - wget https://apt.puppet.com/puppet-tools-release-focal.deb
  - sudo dpkg -i puppet-tools-release-focal.deb
  - sudo apt-get update
  - sudo apt-get install pdk
build: false
test_script:
  - pdk validate --puppet-version=7 'puppet,metadata,yaml'
notifications:
  - provider: Email
    to:
      - puppet-modulebouw@kpn.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
