---
version: 1.1.x.{build}
branches:
  only:
    - master
    - upgrade
skip_commits:
  message: /^\(?doc\)?.*/
platform:
  - x64
configuration: Debug
clone_depth: 10
image:
  - 'Visual Studio 2019'
  - 'Ubuntu2004'
install:
  - wget https://apt.puppet.com/puppet-tools-release-focal.deb
  - sudo dpkg -i puppet-tools-release-focal.deb
  - sudo apt-get update
  - sudo apt-get install pdk=3.0.0 -y
build: false
test_script:
  - pdk validate --parallel
  - pdk test unit --parallel
notifications:
  - provider: Email
    to:
      - puppet-modulebouw@kpn.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
